sudo: required
dist: trusty

services:
  - docker

before_install:
 - docker build .

script:
 - curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "TRAVIS_BRANCH"}' -X POST https://registry.hub.docker.com/u/fundor333/hugo/trigger/77331c49-6765-4c40-9dbe-78f6e23f5c34/
